---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: logging
  labels:
    kubernetes.io/metadata.name: logging
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.8
    helm.sh/chart: fluent-bit-0.20.8
  name: fluent-bit
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.8
    helm.sh/chart: fluent-bit-0.20.8
  name: fluent-bit
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - nodes
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.8
    helm.sh/chart: fluent-bit-0.20.8
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: logging
---
apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        DB /var/log/fluentbit.db

    [FILTER]
        Name              grep
        Match             kube.*
        Regex             message .+

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Annotations Off
        Labels On
        Use_Kubelet On
        Kubelet_Host ${KUBELET_HOST}
        tls.verify Off
        Buffer_Size 0
        Cache_Use_Docker_Id On
        Kube_Meta_Cache_TTL 10m

    [OUTPUT]
        Name                    stackdriver
        Match                   kube.*
        Resource                k8s_container
        k8s_cluster_name        ${CLUSTERNAME}
        k8s_cluster_location    ${CLUSTERLOCATION}
        google_service_credentials  /etc/cloud_sa/gsa.json
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.8
    helm.sh/chart: fluent-bit-0.20.8
  name: fluent-bit
  namespace: logging
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.8
    helm.sh/chart: fluent-bit-0.20.8
  name: fluent-bit
  namespace: logging
spec:
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
  type: ClusterIP
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  creationTimestamp: null
  name: logging
preemptionPolicy: PreemptLowerPriority
value: 1100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.8
    helm.sh/chart: fluent-bit-0.20.8
  name: fluent-bit
  namespace: logging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: fluent-bit
      app.kubernetes.io/name: fluent-bit
  template:
    metadata:
      annotations:
        checksum/config: 1a6aaad01ca6d3fe419a0934bc845ba87ab6a5ab116bb94615ea68549aad0a6c
        checksum/luascripts: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        fluentbit.io/exclude: "true"
      labels:
        app: fluentbit
        app.kubernetes.io/instance: fluent-bit
        app.kubernetes.io/name: fluent-bit
        k8s-app: fluent-bit-logging
    spec:
      containers:
      - env:
        - name: CLUSTERNAME
          valueFrom:
            configMapKeyRef:
              name: clusterconfig
              key: cluster.name
        - name: CLUSTERLOCATION
          valueFrom:
            configMapKeyRef:
              name: clusterconfig
              key: cluster.location
        - name: KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: cr.fluentbit.io/fluent/fluent-bit:1.9.8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: fluent-bit
        ports:
        - containerPort: 2020
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /fluent-bit/etc/fluent-bit.conf
          name: config
          subPath: fluent-bit.conf
        - mountPath: /fluent-bit/etc/custom_parsers.conf
          name: config
          subPath: custom_parsers.conf
        - mountPath: /var/log
          name: varlog
        - mountPath: /etc/cloud_sa
          name: cloud-sa-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: false
      priorityClassName: logging
      serviceAccountName: fluent-bit
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - configMap:
          name: fluent-bit
        name: config
      - hostPath:
          path: /var/log
        name: varlog
      - name: cloud-sa-volume
        secret:
          defaultMode: 420
          secretName: fluentbit-sa
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.8
    helm.sh/chart: fluent-bit-0.20.8
  name: fluent-bit
  namespace: logging
spec:
  ingress: null
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: fluent-bit
      app.kubernetes.io/name: fluent-bit
  policyTypes:
  - Ingress
