apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: paloalto
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noc-k8slabels-v1
  namespace: paloalto
---
apiVersion: scheduling.k8s.io/v1
description: palo alto user-id label updater
kind: PriorityClass
metadata:
  name: labelupdater
preemptionPolicy: PreemptLowerPriority
value: 1200
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: noc-k8slabels-lease
  namespace: paloalto
rules:
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - k8slabel
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noc-k8slabels-v1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: noc-k8slabels
  namespace: paloalto
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: noc-k8slabels-lease
subjects:
- kind: ServiceAccount
  name: noc-k8slabels-v1
  namespace: paloalto
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: noc-k8slabels-v1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: noc-k8slabels-v1
subjects:
- kind: ServiceAccount
  name: noc-k8slabels-v1
  namespace: paloalto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: noc-k8slabels-v1
  name: noc-k8slabels-v1
  namespace: paloalto
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: noc-k8slabels-v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: noc-k8slabels-v1
    spec:
      containers:
      - command:
        - /server
        - --inifile=/secrets/env.ini
        image: ghcr.io/on2itsecurity/noc-k8slabels-v1:latest@sha256:c2eb841683fdb3134adeba91e65ca57dd973612f75d1ef16139abb14fe737442
        name: noc-k8slables-v1
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 30m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10100
        ports:
        - containerPort: 9090
          name: prometheus
          protocol: TCP
        volumeMounts:
        - mountPath: /secrets
          name: envini
      serviceAccountName: noc-k8slabels-v1
      priorityClassName: labelupdater
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: noc-k8slabels-v1
            topologyKey: topology.kubernetes.io/zone
      volumes:
      - name: envini
        secret:
          secretName: noc-k8slabels-v1
          optional: false
